apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-demo
  name: hello-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: hello-demo
  type: NodePort
